# Generated by Django 4.2.7 on 2026-03-20 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('action', models.CharField(choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force'), ('SQL_INJECTION', 'SQL Injection'), ('XSS', 'Cross-Site Scripting'), ('UNAUTHORIZED', 'Unauthorized Access'), ('IP_BLOCKED', 'IP Blocked'), ('INVALID_TOKEN', 'Invalid API Token')], max_length=50)),
                ('layer', models.CharField(choices=[('IaaS', 'Infrastructure Layer'), ('PaaS', 'Platform Layer'), ('SaaS', 'Application Layer')], max_length=10)),
                ('status', models.CharField(choices=[('BLOCKED', 'Blocked'), ('ALLOWED', 'Allowed'), ('WARNING', 'Warning')], max_length=10)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
